In [1]:
import tensorflow as tf
a=tf.constant(5)
b=tf.constant(3)
sum=tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(sum))

8


In [3]:
import tensorflow as tf
a=tf.constant(3.0)
b=tf.constant(8.0)
sum=tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(sum))

11.0


In [4]:
import tensorflow as tf
a=tf.constant(4.0)
b=tf.constant(7.0)
sum=tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(sum))

11.0


In [13]:
from sklearn.feature_extraction import DictVectorizer
dict=DictVectorizer(sparse=False)
data=[{'city':'北京','temperature':10},
     {'city':'深圳','temperature':30},
     {'city':'上海','temperature':50}]
result=dict.fit_transform(data)
print(dict.get_feature_names())
print(result)

['city=上海', 'city=北京', 'city=深圳', 'temperature']
[[ 0.  1.  0. 10.]
 [ 0.  0.  1. 30.]
 [ 1.  0.  0. 50.]]


In [18]:
from sklearn.feature_extraction import DictVectorizer
dict=DictVectorizer(sparse=False)
data=[{'city':'北京','temperature':40},
     {'city':'武汉','temperature':20},
      {'city':'广州','temperature':50}]
result=dict.fit_transform(data)
print(dict.get_feature_names())
print(result)


['city=北京', 'city=广州', 'city=武汉', 'temperature']
[[ 1.  0.  0. 40.]
 [ 0.  0.  1. 20.]
 [ 0.  1.  0. 50.]]


In [17]:
import tensorflow as tf
a=tf.constant(2.0)
b=tf.constant(8.0)
sum=tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(sum))

10.0
